"""Initial migration

Revision ID: 5fdf99baade6
Revises: 
Create Date: 2026-03-01 19:21:34.980970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdf99baade6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_counties_county_name'), 'counties', ['county_name'], unique=False)
    op.create_index(op.f('ix_donations_donation_id'), 'donations', ['donation_id'], unique=False)
    op.create_index(op.f('ix_donors_donor_id'), 'donors', ['donor_id'], unique=False)
    op.create_index(op.f('ix_election_cycles_election_year'), 'election_cycles', ['election_year'], unique=False)
    op.create_index(op.f('ix_simulation_parameters_parameter'), 'simulation_parameters', ['parameter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_parameters_parameter'), table_name='simulation_parameters')
    op.drop_index(op.f('ix_election_cycles_election_year'), table_name='election_cycles')
    op.drop_index(op.f('ix_donors_donor_id'), table_name='donors')
    op.drop_index(op.f('ix_donations_donation_id'), table_name='donations')
    op.drop_index(op.f('ix_counties_county_name'), table_name='counties')
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates')
    # ### end Alembic commands ###
